name: Hello

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-24.04
    steps:
      - name: saludar
        run: echo "Hello, World!"

      - name: ver archivos disponibles
        run: ls -la

      - name: despedida
        run: echo "Goodbye, World!"

      - name: ver variables de entorno
        run: env
