name: 01 - Hello

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-24.04
    steps:
      - name: saludar
        run: echo "Hello, World!"

      - name: ver archivos disponibles
        run: ls -la

      - name: despedida
        run: echo "Goodbye, World!"

      - name: ver variables de entorno
        run: env

  repo-files:
    runs-on: ubuntu-24.04
    steps:
      - name: descargar código del repositorio
        uses: actions/checkout@v3
        
      - name: ver archivos del repositorio
        run: ls -la
